all:
  vars:
    ansible_ssh_user: linux-adm
    become_method: sudo
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    Server:
      hosts:
        server:
          ansible_host: 10.2.16.199
    students:
      hosts:
        student[1:21].local:
      children:
        test:
          hosts:
            student15.local:
        bad:
          hosts: 
            student1.local:
      vars:
