all:
  vars:
    ansible_ssh_user: linux-adm
    become_method: sudo
    ansible_ssh_private_key_file: .ssh/id_rsa
  children:
    Server:
      hosts:
        localhost:
          ansible_connection: local
    Test:
      hosts:
        test:
          ansible_host: 192.168.122.99
    Learning:
      children:
        Teachers:
          hosts:
            test:
          vars:
        Virtualization:
          vars:
          hosts:
            test:
        Networks:
        Programming: