all:
  vars:
    ansible_ssh_user: linux-adm
    become_method: sudo
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    ipaservers:
      hosts:
        server:
          ansible_host: 192.168.122.77
      vars:
        ipaadmin_password: ADMPassword1
        ipadm_password: DMPassword1
        ipaserver_domain: ithub.lab
        ipaserver_realm: ITHUB.LAB
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: yes
