all:
  vars:
    ansible_ssh_user: linux-adm
    become_method: sudo
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ipaadmin_principal: admin
    ipaadmin_password: ADMPassword1
    ipadm_password: DMPassword1
    ipaserver_domain: ithub.lab
    ipaserver_realm: ITHUB.LAB
    ipaserver_setup_dns: yes
    ipaserver_auto_forwarders: yes
    ipaclient_servers: serv.ithub.lab
    ipaclient_domain: ithub.lab
    ipaclient_realm: ITHUB.LAB
    ipaclient_configure_dns_resolver: yes
    ipaclient_dns_servers: 192.168.122.77
  children:
    ipaservers:
      hosts:
        serv.ithub.lab:
          ansible_host: 192.168.122.77
      vars:
        ipaadmin_password: ADMPassword1
        ipadm_password: DMPassword1
        ipaserver_domain: ithub.lab
        ipaserver_realm: ITHUB.LAB
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: yes
    ipaclients:
      hosts:
        student1.cab.ithub.lab:
      vars:
        ipaclient_servers: serv.ithub.lab
        ipaclient_domain: ithub.lab
        ipaclient_realm: ITHUB.LAB
        ipaclient_configure_dns_resolver: yes
        ipaclient_dns_servers: 192.168.122.77
        ipaclient_allow_repair: yes
        ipaclient_mkhomedir: yes
