---
- name: Install FreeIPA packages
  yum:
    name:
      - ipa-server
      - ipa-server-dns
      - ipa-server-trust-ad
    state: present

- name: Configure hostname
  hostname:
    name: "{{ ipa_server_hostname }}"
  become: true

- name: Configure SELinux
  selinux:
    policy: targeted
    state: enforcing
  become: true

- name: Setup FreeIPA server
  ipa_server_install:
    ip_address: "{{ ipa_server_ip_address }}"
    domain: "{{ ipa_server_hostname | regex_replace('\\..*', '') }}"
    realm: "{{ ipa_server_hostname | upper }}"
    admin_password: "{{ ipa_admin_password }}"
    allow_zone_overlap: true
    allow_zone_forwarders: true
  become: true 

